### ISSUE TITLE
Failed to exec start script - Windows 7 64bit

### ISSUE THREAD

**Issue by tekzoom** [badsyntax/react-seed#22]
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\User1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.13.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-seed@0.0.16
6 verbose unsafe-perm in lifecycle true
7 info start react-seed@0.0.16
8 verbose unsafe-perm in lifecycle true
9 info react-seed@0.0.16 Failed to exec start script
10 verbose stack Error: react-seed@0.0.16 start: `NODE_ENV=development node dev-server ./webpack/config`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Users\User1\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-seed@0.0.16
12 verbose cwd C:\repo\my-project
13 error Windows_NT 6.1.7601
14 error argv "node" "C:\\Users\\User1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.7
16 error npm  v2.13.3
17 error code ELIFECYCLE
18 error react-seed@0.0.16 start: `NODE_ENV=development node dev-server ./webpack/config`
18 error Exit status 1
19 error Failed at the react-seed@0.0.16 start script 'NODE_ENV=development node dev-server ./webpack/config'.
19 error This is most likely a problem with the react-seed package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     NODE_ENV=development node dev-server ./webpack/config
19 error You can get their info via:
19 error     npm owner ls react-seed
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by badsyntax** [comment]
thanks for letting me know! tbh i have not tested this project at all on windows. i will now test on windows and fix these issues over the weekend.

**Comment by badsyntax** [comment]
TODO:

* Fix the npm-scripts (set env vars)
* Check why dev server doesn't start

**Comment by tmkbry** [comment]
Had a similar problem under Windows 10. I changed the the following within package.json:

```javascript
"scripts": {
    ...
    "start": "set NODE_ENV=development && node dev-server ./webpack/config",
}
```

**Comment by sevaru** [comment]
@tmkbry I do the same. But it seems like auto refresh does not work. e.g. I change lines in Body.jsx but browser not reloaded? Is it a bug on windows or I just do something wrong? (windows 10 64, node 4.2, npm 2.14.7)

**Comment by tmkbry** [comment]
@sevaru try the following.  
```
"start": "set NODE_ENV=development&node dev-server ./webpack/config",
```

That fixed the reload bug for me and for some reason it does give me way faster recompile time.
Btw I'm using the latest version of node.

**Comment by greeze** [comment]
`npm run env NODE_ENV=production`

Should be compatible with both Windows and *nix environments. I'm not on my Mac at the moment, so I can't test it, but it's working on Windows.
