### ISSUE TITLE
Created new project got Eslint error

### ISSUE THREAD

**Issue by ospfranco** [badsyntax/react-seed#35]
Created a new project from seed using Yeoman, when I open the project in atom I get:

```Error: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
TypeError: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
    at Function.componentRule (/Users/osp/dev/mantro/node_modules/eslint-plugin-react/lib/util/Components.js:109:28)
    at /Users/osp/dev/mantro/node_modules/eslint/lib/eslint.js:628:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/osp/dev/mantro/node_modules/eslint/lib/eslint.js:619:16)
    at processText (/Users/osp/dev/mantro/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/Users/osp/dev/mantro/node_modules/eslint/lib/cli-engine.js:361:26)
    at Object.execute (/Users/osp/dev/mantro/node_modules/eslint/lib/cli.js:179:36)
    at lintJob (/Users/osp/.atom/packages/linter-eslint/lib/worker.js:37:10)
    at /Users/osp/.atom/packages/linter-eslint/lib/worker.js:71:20
    at Emitter.emit (/Users/osp/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:70:19)```

any idea what might be going on, I saw the dependency for eslint is quite low: 0.24.1, maybe this could be the problem?

**Comment by ospfranco** [comment]
Seems `.eslintrc` is not created with yeoman? anyways I added one (and had to configure it!) and error seems to be gone!
